### ISSUE TITLE
Stops working after a number of questions

### ISSUE THREAD

**Issue by Purto1** [cooljingle/memrise-audio-provider#8]
Not originally a problem. The audio-provider now ceases to work (with the item even disappearing from the screen) after several questions of either review or learn. 

This may be a problem exclusive to Czech.

**Comment by cooljingle** [comment]
This is probably a result of the script relying on google tts, which limits the number of requests you make in a certain time period. There is a workaround though - Chrome has support for local tts services; if these are found the script will prioritize those instead. I've just tested on Windows and it works - go to Windows Speech settings and add the voice package for Czech, then restart your browser.

**Comment by Purto1** [comment]
Hey it's all good. I actually ended up finding a work around. I am no coder (at all), but I added ""Czech": "cs-CZ"" and ""Czech": "cs-cz"" to the Speech Synthesis Language Codes and Voice RSS language code "paragraphs" and it seems to be working fine, albeit with a different voice. Sorry for the spam, and thanks for the help.
